name: firebase_admob
description: Flutter plugin for Firebase AdMob, supporting
  banner, interstitial (full-screen), and rewarded video ads
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob
version: 0.11.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebaseadmob
        pluginClass: FirebaseAdMobPlugin
      ios:
        pluginClass: FLTFirebaseAdMobPlugin
