name: firebase_ml_custom_example
description: Demonstrates how to use the firebase_ml_custom plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  firebase_ml_custom:
    path: ../
  flutter:
    sdk: flutter
  image_picker: ^0.7.4

dev_dependencies:
  drive: 0.1.0
  flutter_driver:
    sdk: flutter
  path_provider: ^0.5.0+1
  test: any

flutter:
  uses-material-design: true

  assets:
    - assets/labels_mobilenet_v1_224.txt
