name: firebase_admob_example
description: Demonstrates how to use the firebase_admob plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_admob:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
