name: firebase_app_check_web
description: The web implementation of firebase_auth
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check_web
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  firebase_app_check_platform_interface: ^0.0.1
  firebase_core: ^1.1.0
  firebase_core_web: ^1.0.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  firebase_app_check:
    path: ../firebase_app_check
  firebase_core_platform_interface: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAppCheckWeb
        fileName: firebase_app_check_web.dart
