name: firebase_ml_custom
description: Flutter plugin for Firebase Machine Learning Custom Model support.
version: 0.2.0+1
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_custom
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_custom

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebasemlcustom
        pluginClass: FirebaseMLCustomPlugin
      ios:
        pluginClass: FLTFirebaseMLCustomPlugin
